mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.szss.shardingjdbc.demo.domain

sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0
        username: root
        password: 123456
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1
        username: root
        password: 123456
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds$->{user_id % 2}
        tables:
          t_user:
            actual-data-nodes: ds$->{0..1}.t_user_$->{0..2}
            table-strategy:
              inline:
                sharding-column: user_id
                algorithm-expression: t_user_$->{user_id % 3}
            key-generator-column-name: user_id
        props:
          sql:
            show: true

# 日志
logging:
  level:
    root: INFO
    com.szss: DEBUG
    java.sql: DEBUG
    org.mybatis: DEBUG
    io.shardingsphere: DEBUG
